baseURL: https://yiyuehu.netlify.app/
languageCode: en-us
title: Portfolio website for Yiyue Hu
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner:
    buttonText: Get Started
    subtitle: |-
      MFA2022 student at LBS
    title: Hi, my name is Yiyue Hu
  blog: {}
  contact:
    address:
      - city: London
        country: UK
        street: Regent's Park, NW1 4SA
        title: Address
    buttonClear: Clear
    buttonSend: Send message
    email:
      - email: yhu.mfa2022@london.edu
        title: Email
    enable: yes
    phone:
      - phone: (44) 7720587474
        title: Phone
  custom_css: []
  custom_js: []
  description: Your description
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer:
    copyright: Yiyue Hu
    enable: yes
    quicklinks:
      - alt: HTML5 UP
        text: 'Design: '
        url: https://www.html5up.net
    social:
##      - icon: fa-twitter
##        label: Twitter
##        url: https://www.twitter.com
##      - icon: fa-facebook 
##        label: Facebook 
##        url: https://www.facebook.com
      - icon: fa-instagram 
        label: Instagram
        url: https://www.instagram.com/hubobo_/
      - icon: fa-github
        label: GitHub
        url: https://github.com/YiyueHu68
      - icon: fa-linkedin
        label: LinkedIn 
        url: https://www.linkedin.com/in/yiyue-h-816b56197/
  image: ''
  name: Your name
  navigation:
    button1:
      - name: Get Started
        url: blogs
    button2:
      - name: Log In
        url: '#'
    links:
      - name: Home
        url: '#'
      - name: Contents
        url: blogs
##      - name: Generic Blog
##        url: blogs/ipsum
##      - name: Elements
##        url: elements.html
    menu: Menu
    subtitle: Personal Website
    title: Yiyue Hu
  tiles:
    enable: yes
    showcase:
      - image: lbs.jpg
        subtitle: My biology
        title: About Me
        url: blogs/my_intro
      - image: CAPM1.jpeg
        subtitle: Explore yearly change of US CPI and its components
        title: How has the CPI and its components changed over the last few years?
        url: blogs/cpi
      - image: weather.jpeg
        subtitle: Explore Weather Anomalies
        title: Climate change and temperature anomalies
        url: blogs/weather
      - image: fudan.jpg
        subtitle: Official Website of my undergraduate university, Fudan University
        title: Fudan University
        url: https://www.fudan.edu.cn/en/
      - image: shanghai2.jpeg
        subtitle: An Introduction to my hometown
        title: About Shanghai
        url: blogs/Shanghai
      - image: wsj.png
        subtitle: An Article Published in WALL STREET JOURNAL
        title: Companies Strike While the Stock Market Is Hot
        url: /img/blogs/stock.pdf
  two:
    buttonText: Get Started
    enable: yes
    subtitle: "I was born and raised in Shanghai, China. I enjoy travelling and I've been to nearly 30 countries all over the world!
    In my free time, I enjoy skiing, listening to music and learning languages."
    title: Something about me
    url: blogs
